### get peaks
GET http://127.0.0.1:8080/api/products HTTP/1.1

### get peak by id
GET http://127.0.0.1:8080/api/products/1 HTTP/1.1

# ### post votes
# POST http://127.0.0.1:3000/api/votes HTTP/1.1
# Content-Type: "application/json"

# { "vote": "up"}
###
